services:
  - type: web
    name: rag-pdf-chatbot
    runtime: python
    pythonVersion: "3.12.0"
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 120
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: COLLECTION_NAME
        value: pdf_rag_collection